#!/bin/sh 
if [ -f "/usr/local/lib/audacious/General/mylyric.so" ]
then
    rm /usr/local/lib/audacious/General/mylyric.so && echo "删除文件mylyric.so"
fi

cp mylyric.so /usr/local/lib/audacious/General/mylyric.so && echo "复制文件mylyric.so到目标"
