#!/bin/sh 
if [ ! -s "/usr/lib/x86_64-linux-gun/audacious/General/mylyric.so" ]
then
    rm /usr/lib/x86_64-linux-gnu/audacious/General/mylyric.so && echo "删除文件mylyric.so"
fi

cp mylyric.so /usr/lib/x86_64-linux-gnu/audacious/General/mylyric.so && echo "复制文件mylyric.so到目标"
chmod u+s /usr/lib/x86_64-linux-gnu/audacious/General/mylyric.so 
